name: App Build

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  AWS_DEFAULT_REGION: eu-west-1
  ECR_REPO: house-counter-tags

jobs:
  get-ref-name:
    runs-on: ubuntu-latest
    outputs:
      ref_name: ${{ steps.get-ref-name.outputs.ref_name }}
    steps:
      - name: Get ref_name
        id: get-ref-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            sanitized_ref=$(echo ${{ github.head_ref }} | sed 's/[^a-zA-Z0-9.]/-/g')
          elif [ "${{ github.event_name }}" == "create" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            sanitized_ref=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9.]/-/g')
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            sanitized_ref="manual-${GITHUB_SHA::7}"
          else
            sanitized_ref=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9.]/-/g')
          fi
          echo "ref_name=$sanitized_ref" >> $GITHUB_OUTPUT

  build_feature:
    needs: [get-ref-name]
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push house-counter image to Amazon ECR
        id: docker_build_house_counter
        env:
          ECR_URL: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ needs.get-ref-name.outputs.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: house-counter
          file: house-counter/Dockerfile
          provenance: false
          build-args: |
            APP_VERSION=${{ env.IMAGE_TAG }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
          cache-from: type=gha,scope=house-counter
          cache-to: type=gha,mode=max,scope=house-counter
          push: true
          tags: |
            ${{ env.ECR_URL }}/${{ env.ECR_REPO }}:house-counter-${{ env.IMAGE_TAG }}

      - name: Build, tag, and push front-back-garden image to Amazon ECR
        id: docker_build_front_back_garden
        env:
          ECR_URL: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ needs.get-ref-name.outputs.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: front-back-garden
          file: front-back-garden/Dockerfile
          provenance: false
          build-args: |
            APP_VERSION=${{ env.IMAGE_TAG }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
          cache-from: type=gha,scope=front-back-garden
          cache-to: type=gha,mode=max,scope=front-back-garden
          push: true
          tags: |
            ${{ env.ECR_URL }}/${{ env.ECR_REPO }}:front-back-garden-${{ env.IMAGE_TAG }}

      - name: Build, tag, and push nginx image to Amazon ECR
        id: docker_build_nginx
        env:
          ECR_URL: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ needs.get-ref-name.outputs.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: nginx
          file: nginx/Dockerfile
          provenance: false
          build-args: |
            APP_VERSION=${{ env.IMAGE_TAG }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
          cache-from: type=gha,scope=nginx
          cache-to: type=gha,mode=max,scope=nginx
          push: true
          tags: |
            ${{ env.ECR_URL }}/${{ env.ECR_REPO }}:nginx-${{ env.IMAGE_TAG }}